"use client";
import { useEffect, useState } from "react";
import { ArrowsClockwise, CornersOut, Medal, Play, ArrowCounterClockwise } from "@phosphor-icons/react";
import Shell from "../../components/Shell";
import { api } from "../../components/api";
import type { Player } from "../../components/types";
type Team="A"|"B"; type Game={id?:string;status:"active"|"finished";mode:string;bestOf:number;target:number;names:Record<Team,string>;teams:Record<Team,Player[]>;rotation:Record<Team,string[]>;score:Record<Team,number>;sets:Array<{a:number;b:number}>;server:Team;undo:any[];mvp?:string};
export default function Score(){const [players,setPlayers]=useState<Player[]>([]);const [game,setGame]=useState<Game|null>(null);const [bestOf,setBestOf]=useState(3);const [target,setTarget]=useState(25);const [mode,setMode]=useState("5x1");useEffect(()=>{api<Player[]>("/players").then(setPlayers);api<any[]>("/matches").then(m=>{const active=m.find(x=>x.status==="active");if(active)setGame({...active.data,id:active.id})})},[]);
 async function persist(g:Game){setGame(g);const r=await api<{id:string}>("/matches",{method:"POST",body:JSON.stringify({id:g.id,status:g.status,data:{...g,id:undefined}})});if(!g.id)setGame({...g,id:r.id})}
 function start(){if(players.length<4)return alert("Cadastre pelo menos 4 jogadores.");const teams:{A:Player[];B:Player[]}={A:[],B:[]};[...players].sort(()=>Math.random()-.5).forEach((p,i)=>teams[i%2?"B":"A"].push(p));persist({status:"active",mode,bestOf,target,names:{A:"Time A",B:"Time B"},teams,rotation:{A:teams.A.slice(0,6).map(p=>p.id),B:teams.B.slice(0,6).map(p=>p.id)},score:{A:0,B:0},sets:[],server:"A",undo:[]})}
 function rotate(ids:string[]){return ids.length>1?[ids.at(-1)!,...ids.slice(0,-1)]:ids} function point(team:Team){if(!game)return;const g=structuredClone(game);g.undo.push({score:{...g.score},server:g.server,rotation:structuredClone(g.rotation),sets:[...g.sets]});if(g.undo.length>30)g.undo.shift();if(g.server!==team){g.server=team;g.rotation[team]=rotate(g.rotation[team])}g.score[team]++;const other=team==="A"?"B":"A";const deciding=g.sets.length===g.bestOf-1&&g.bestOf>1;const limit=deciding?15:g.target;if(g.score[team]>=limit&&g.score[team]-g.score[other]>=2){g.sets.push({a:g.score.A,b:g.score.B});g.score={A:0,B:0};const wins=g.sets.filter(s=>s.a>s.b).length;const losses=g.sets.filter(s=>s.b>s.a).length;if(wins>g.bestOf/2||losses>g.bestOf/2)g.status="finished"}persist(g)}
 function undo(){if(!game?.undo.length)return;const g=structuredClone(game),u=g.undo.pop();Object.assign(g,u);persist(g)} function swap(team:Team,index:number){if(!game)return;const g=structuredClone(game),ids=g.rotation[team];if(index<ids.length-1)[ids[index],ids[index+1]]=[ids[index+1],ids[index]];persist(g)}
 if(!game)return <Shell><div className="page-head"><div><p className="eyebrow">NOVA PARTIDA</p><h1>Placar</h1><p>Configure a partida; o andamento será salvo automaticamente.</p></div></div><section className="panel score-config"><label>Modo<select value={mode} onChange={e=>setMode(e.target.value)}><option value="5x1">5x1</option><option value="fixo">Levantador fixo</option><option value="6x0">6x0</option></select></label><label>Melhor de<select value={bestOf} onChange={e=>setBestOf(+e.target.value)}><option value="1">1 set</option><option value="3">3 sets</option><option value="5">5 sets</option></select></label><label>Pontos por set<input type="number" min="5" max="50" value={target} onChange={e=>setTarget(+e.target.value)}/></label><button className="primary" onClick={start}><Play/> Iniciar com elenco</button></section></Shell>;
 return <Shell><div className="page-head"><div><p className="eyebrow">{game.status==="active"?"PARTIDA EM ANDAMENTO":"PARTIDA ENCERRADA"}</p><h1>Placar ao vivo</h1><p>Set {game.sets.length+1} · {game.mode}</p></div><div className="button-row"><button className="primary" onClick={()=>document.documentElement.requestFullscreen()}><CornersOut/> Tela cheia</button><button className="secondary-btn" onClick={undo}><ArrowCounterClockwise/> Desfazer</button></div></div><div className="live-score">{(["A","B"] as Team[]).map(t=><section className={`score-team ${game.server===t?"serving":""}`} key={t}><small>{game.server===t?"● SACANDO":"EQUIPE"}</small><h2>{game.names[t]}</h2><strong>{game.score[t]}</strong><button disabled={game.status==="finished"} onClick={()=>point(t)}>+1 PONTO</button><div className="court">{game.rotation[t].map((id,i)=>{const p=game.teams[t].find(x=>x.id===id);return <button key={id} onClick={()=>swap(t,i)}><b>{p?.number}</b><span>{p?.name}</span><i>{i+1}</i></button>})}</div><div className="roster">{game.teams[t].map(p=><label key={p.id}><input type="radio" name="mvp" checked={game.mvp===p.id} onChange={()=>persist({...game,mvp:p.id})}/><Medal/>{p.name}</label>)}</div></section>)}</div><div className="set-strip">{game.sets.map((s,i)=><span key={i}>Set {i+1}: <b>{s.a} × {s.b}</b></span>)}</div>{game.status==="finished"&&<button className="primary new-match" onClick={()=>setGame(null)}><ArrowsClockwise/> Nova partida</button>}</Shell>}
