"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowsClockwise, Minus, Plus, Trophy } from "@phosphor-icons/react";
import Shell from "../../components/Shell";
import { api } from "../../components/api";
import type { Player } from "../../components/types";
import { defaultWeights, normalizeWeights, weightedSkill, type Weights } from "../../components/weights";
function makeTeams(players:Player[],count:number,mode:string,criterion:string,weights:Weights){let best:Player[][]=[],bestScore=Infinity;for(let attempt=0;attempt<700;attempt++){const teams=Array.from({length:count},()=>[] as Player[]);[...players].sort((a,b)=>criterion==="random"?Math.random()-.5:weightedSkill(b,weights,mode)-weightedSkill(a,weights,mode)).forEach((p,i)=>teams[i%count].push(p));const avgs=teams.map(t=>t.reduce((s,p)=>s+weightedSkill(p,weights,mode),0)/t.length);const spread=Math.max(...avgs)-Math.min(...avgs);const positions=criterion==="skill"?0:teams.reduce((cost,t)=>cost+(t.some(p=>(mode==="rachao"?p.positionR:p.position5||p.position)==="Levantador")?0:8),0);const score=spread+positions;if(score<bestScore){bestScore=score;best=teams}}return best}
const position=(p:Player,mode:string)=>(mode==="rachao"?p.positionR:p.position5)||p.position;
function SelectionCard({player,mode,weights,remove}:{player:Player;mode:string;weights:Weights;remove:()=>void}){const skill=weightedSkill(player,weights,mode);const stats=[player.set,player.pass,player.attack,player.serve,player.block,player.physical??50];return <article className="draw-card"><div className="draw-card-photo">{player.photo?<img src={player.photo} alt={player.name}/>:<span>{player.name[0]}</span>}<strong>{skill}</strong></div><div className="draw-card-body"><small>#{String(player.number).padStart(2,"0")} · {position(player,mode)}</small><b>{player.name}</b><div className="draw-card-bars">{stats.map((v,i)=><i key={i}><em style={{width:`${v}%`}}/></i>)}</div></div><button onClick={remove} aria-label={`Remover ${player.name}`}><Minus/></button></article>}
export default function Draw(){const [players,setPlayers]=useState<Player[]>([]);const [weights,setWeights]=useState<Weights>(defaultWeights);const [selected,setSelected]=useState<string[]>([]);const [count,setCount]=useState(2);const [perTeam,setPerTeam]=useState(6);const [mode,setMode]=useState("5x1");const [criterion,setCriterion]=useState("hybrid");const [teams,setTeams]=useState<Player[][]>([]);useEffect(()=>{api<Player[]>("/players").then(setPlayers);api<any>("/card-config").then(c=>setWeights(normalizeWeights(c.weights)))},[]);const chosen=useMemo(()=>players.filter(p=>selected.includes(p.id)),[players,selected]);const available=useMemo(()=>players.filter(p=>!selected.includes(p.id)),[players,selected]);const add=(id:string)=>setSelected(s=>s.includes(id)?s:[...s,id]);const remove=(id:string)=>setSelected(s=>s.filter(x=>x!==id));async function draw(){if(chosen.length<count*perTeam)return alert(`Adicione pelo menos ${count*perTeam} jogadores à lista.`);const result=makeTeams(chosen,count,mode,criterion,weights).map(t=>t.slice(0,perTeam));setTeams(result);await api("/history",{method:"POST",body:JSON.stringify({data:{teams:result,mode,criterion,count,perTeam}})})}
return <Shell><div className="page-head"><div><p className="eyebrow">EQUILÍBRIO INTELIGENTE</p><h1>Sorteio de times</h1><p>Adicione os participantes e confira seus cards antes do sorteio.</p></div><button className="primary" onClick={draw}><ArrowsClockwise/> Sortear times</button></div><div className="draw-layout"><section className="panel"><div className="panel-title"><h2>Lista do jogo <span>{chosen.length}/{count*perTeam}</span></h2><button className="text-btn" onClick={()=>setSelected(chosen.length?[]:players.map(p=>p.id))}>{chosen.length?"Limpar":"Adicionar todos"}</button></div><div className="selected-cards">{chosen.map(p=><SelectionCard key={p.id} player={p} mode={mode} weights={weights} remove={()=>remove(p.id)}/>)}{!chosen.length&&<div className="selection-empty">Use <b>Adicionar</b> para montar a lista.</div>}</div><h3 className="available-title">Jogadores disponíveis</h3><div className="available-list">{available.map(p=><article key={p.id}><span>{p.photo?<img src={p.photo} alt=""/>:<i>{p.name[0]}</i>}<b>{p.name}</b><small>{position(p,mode)} · PS {weightedSkill(p,weights,mode)}</small></span><button onClick={()=>add(p.id)}><Plus/> Adicionar</button></article>)}</div><div className="draw-settings"><label className="team-count">Times<select value={count} onChange={e=>setCount(+e.target.value)}><option value="2">2 times</option><option value="3">3 times</option><option value="4">4 times</option></select></label><label className="team-count">Jogadores por time<input type="number" min="2" max="12" value={perTeam} onChange={e=>setPerTeam(+e.target.value)}/></label><label className="team-count">Modo<select value={mode} onChange={e=>setMode(e.target.value)}><option value="5x1">5x1</option><option value="rachao">Rachão</option></select></label><label className="team-count">Critério<select value={criterion} onChange={e=>setCriterion(e.target.value)}><option value="hybrid">Habilidades + posições</option><option value="skill">Somente habilidades</option><option value="random">Aleatório equilibrado</option></select></label></div></section><section className="team-results">{teams.length?teams.map((team,i)=><article className={`team t${i}`} key={i}><header><span><Trophy/></span><div><small>TIME {String.fromCharCode(65+i)}</small><h2>{(team.reduce((s,p)=>s+weightedSkill(p,weights,mode),0)/team.length).toFixed(1)} <i>média PS</i></h2></div></header>{team.map(p=><div className="team-player" key={p.id}><b>{p.number}</b><span>{p.name}<small>{position(p,mode)}</small></span><strong>{weightedSkill(p,weights,mode)}</strong></div>)}</article>):<div className="court-empty"><div>🏐</div><h2>Times ainda não sorteados</h2><p>Monte a lista com {count*perTeam} jogadores e clique em “Sortear times”.</p></div>}</section></div></Shell>}
