"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, FloppyDisk } from "@phosphor-icons/react";
import Shell from "../../../components/Shell";
import { api } from "../../../components/api";
import { overall, type Player, type Session } from "../../../components/types";

const fields=[['set','Levantamento'],['pass','Passe'],['attack','Ataque'],['serve','Saque'],['block','Bloqueio'],['physical','Físico']] as const;
function Radar({player}:{player:Player}){const values=fields.map(([k])=>Number(player[k]??50));const cx=50,cy=50,r=29;const point=(v:number,i:number,rr=r*v/100)=>{const a=-Math.PI/2+i*Math.PI*2/6;return [cx+Math.cos(a)*rr,cy+Math.sin(a)*rr]};const polygon=(vals:number[])=>vals.map((v,i)=>point(v,i).join(',')).join(' ');return <svg className="radar" viewBox="-8 -8 116 116" aria-label="Gráfico de atributos">{[100,75,50,25].map(v=><polygon key={v} className="gridline" points={polygon(fields.map(()=>v))}/>)}{fields.map(([,label],i)=>{const [x,y]=point(100,i,42);return <g key={label}><line className="axis" x1="50" y1="50" x2={point(100,i)[0]} y2={point(100,i)[1]}/><text x={x} y={y} textAnchor={x<45?'end':x>55?'start':'middle'} dominantBaseline="middle">{label}</text></g>})}<polygon className="shape" points={polygon(values)}/>{values.map((v,i)=>{const [x,y]=point(v,i);return <circle key={i} cx={x} cy={y} r="1.5"/>})}</svg>}
export default function Profile(){const {id}=useParams<{id:string}>();const [player,setPlayer]=useState<Player>();const [me,setMe]=useState<Session>();const [saved,setSaved]=useState("");useEffect(()=>{Promise.all([api<Player[]>("/players"),api<Session>("/auth/me")]).then(([p,m])=>{setPlayer(p.find(x=>x.id===id));setMe(m)})},[id]);const skill=useMemo(()=>player?Math.round(((player.position5==="Levantador"?player.set*2:player.attack*2)+player.pass+player.serve+player.block+(player.physical??50))/7):0,[player]);if(!player)return <Shell><div className="loading">Carregando card…</div></Shell>;async function save(){if(!player)return;setSaved("Salvando…");try{await api(`/players/${player.id}`,{method:"PUT",body:JSON.stringify(player)});setSaved("Atributos atualizados no ArcadeDB.")}catch(e){setSaved((e as Error).message)}}return <Shell><Link className="profile-back" href="/jogadores"><ArrowLeft/> Voltar ao elenco</Link><div className="profile-page"><article className="athlete-card"><div className="card-content"><header className="card-head"><div className="card-avatar">{player.photo?<img src={player.photo} alt={player.name}/>:player.name[0]}</div><div className="card-name"><h1>{player.name}</h1><b>🏐 {player.position5||player.position}</b><small>#{String(player.number).padStart(2,'0')}</small></div><div className="card-rating">{overall(player)}</div></header><div className="stat-bars">{fields.map(([k,label])=><div className="stat-row" key={k}><span>{label}</span><div className="stat-track"><i style={{width:`${player[k]??50}%`}}/></div><b>{player[k]??50}</b></div>)}</div><div className="position-skill"><small>POSITION SKILL</small><b>{skill}</b></div><div className="radar-wrap"><Radar player={player}/></div><footer className="card-foot"><span><small>5x1</small><b>{player.position5||player.position}</b></span><span><small>RACHÃO</small><b>{player.positionR||'Geral'}</b></span><span><small>Nº</small><b>{String(player.number).padStart(2,'0')}</b></span></footer></div></article>{me?.role==='admin'?<aside className="panel stats-editor"><p className="eyebrow">EDIÇÃO EXCLUSIVA</p><h2>Atributos</h2><p>Os ajustes aparecem no card e no radar em tempo real. Salve para atualizar o ArcadeDB.</p><div className="editor-fields">{fields.map(([k,label])=><label key={k}>{label}<b>{player[k]??50}</b><input type="range" min="0" max="100" value={player[k]??50} onChange={e=>setPlayer({...player,[k]:+e.target.value})}/></label>)}</div><button className="primary" onClick={save}><FloppyDisk/> Salvar atributos</button>{saved&&<p>{saved}</p>}</aside>:<aside className="readonly-note">Somente administradores podem modificar os atributos. Você pode visualizar o card e o gráfico normalmente.</aside>}</div></Shell>}
