"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Camera, MagnifyingGlass, Plus, X } from "@phosphor-icons/react";
import Shell from "../../components/Shell";
import { api } from "../../components/api";
import { overall, type Player, type Session } from "../../components/types";
const blank = { name: "", number: 0, position: "Ponteiro", position5:"Ponteiro", positionR:"Geral", photo: "", serve: 50, pass: 50, set: 50, attack: 50, block: 50, physical:50, temporary:false };
export default function Players() { const [players, setPlayers] = useState<Player[]>([]); const [me, setMe] = useState<Session>(); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [form, setForm] = useState(blank); const [error, setError] = useState(""); const canEdit = me?.role === "admin" || me?.role === "leader"; const load = () => api<Player[]>("/players").then(setPlayers); useEffect(() => { load(); api<Session>("/auth/me").then(setMe); }, []);
  function photo(file?: File) { if (!file) return; if (file.size > 4_000_000) return setError("A imagem deve ter no máximo 4 MB"); const img = new Image(); img.onload = () => { const canvas = document.createElement("canvas"); const scale = Math.min(1, 700 / Math.max(img.width, img.height)); canvas.width = img.width * scale; canvas.height = img.height * scale; canvas.getContext("2d")!.drawImage(img, 0, 0, canvas.width, canvas.height); setForm({ ...form, photo: canvas.toDataURL("image/webp", .78) }); }; img.src = URL.createObjectURL(file); }
  async function save(e: React.FormEvent) { e.preventDefault(); setError(""); try { await api("/players", { method: "POST", body: JSON.stringify(form) }); setOpen(false); setForm(blank); load(); } catch (e) { setError((e as Error).message); } }
  const filtered = players.filter(p => `${p.name} ${p.position}`.toLowerCase().includes(search.toLowerCase()));
  return <Shell><div className="page-head"><div><p className="eyebrow">ELENCO</p><h1>Jogadores</h1><p>{players.length} atletas cadastrados</p></div>{me && <button className="primary" onClick={() => {setForm({...blank,temporary:me.role==="default"});setOpen(true)}}><Plus/> {canEdit?"Novo jogador":"Jogador temporário"}</button>}</div><div className="toolbar"><MagnifyingGlass/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por nome ou posição…"/></div><div className="player-grid">{filtered.map(p => <article className="player-card" key={p.id}><Link className="photo" href={`/jogadores/${p.id}`} aria-label={`Abrir card de ${p.name}`}>{p.photo ? <img src={p.photo} alt={p.name} loading="lazy"/> : <span>{p.name[0]}</span>}<b>{overall(p)}</b>{p.temporary&&<small className="temporary-badge">TEMPORÁRIO · 24H</small>}<em>Ver card</em></Link><div className="player-info"><small>#{String(p.number).padStart(2, "0")} · {p.position}</small><h3>{p.name}</h3><div className="skills"><i style={{ width: `${overall(p)}%` }}/></div></div></article>)}</div>{!filtered.length && <div className="empty">Nenhum jogador encontrado.</div>}
  {open && <div className="modal"><form className="modal-card" onSubmit={save}><button type="button" className="close" onClick={() => setOpen(false)}><X/></button><p className="eyebrow">NOVO ATLETA</p><h2>Ficha do jogador</h2>{me?.role==="default"&&<p className="temporary-notice">Este perfil será temporário e desaparecerá automaticamente após 24 horas.</p>}<div className="form-grid"><label className="wide">Nome<input required minLength={2} value={form.name} onChange={e => setForm({...form, name:e.target.value})}/></label><label>Número<input inputMode="numeric" type="number" min="0" max="99" value={form.number} onChange={e => setForm({...form, number:+e.target.value})}/></label><label>Posição 5x1<select value={form.position5} onChange={e => setForm({...form, position:e.target.value,position5:e.target.value})}>{["Levantador","Ponteiro","Central","Oposto","Líbero"].map(x => <option key={x}>{x}</option>)}</select></label><label>Posição Rachão<select value={form.positionR} onChange={e=>setForm({...form,positionR:e.target.value})}><option>Geral</option><option>Levantador</option></select></label>{canEdit&&<label className="temporary-choice wide"><input type="checkbox" checked={form.temporary} onChange={e=>setForm({...form,temporary:e.target.checked})}/> Perfil temporário por 24 horas</label>}<label className="upload wide"><Camera/>{form.photo ? "Foto pronta" : "Adicionar foto"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => photo(e.target.files?.[0])}/></label>{canEdit&&(["serve","pass","set","attack","block","physical"] as const).map(k => <label key={k}>{({serve:"Saque",pass:"Passe",set:"Levantamento",attack:"Ataque",block:"Bloqueio",physical:"Físico"})[k]}<input inputMode="numeric" type="number" min="0" max="100" value={form[k]} onChange={e => setForm({...form,[k]:Math.min(100,Math.max(0,+e.target.value))})}/></label>)}</div>{error && <div className="error">{error}</div>}<button className="primary">Salvar jogador</button></form></div>}</Shell>; }
