"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowsLeftRight, CheckCircle, UsersThree } from "@phosphor-icons/react";
import Shell from "../../../components/Shell";
import type { Player } from "../../../components/types";
type Draw={teams:Player[][];mode:string;criterion:string;count:number;perTeam:number;createdAt:string};
const labels=["Posição 4","Posição 3","Posição 2","Posição 5","Posição 6","Posição 1"];
function PlayerToken({p,selected,onClick,draggable=true,onDragStart}:{p:Player;selected:boolean;onClick:()=>void;draggable?:boolean;onDragStart?:(e:React.DragEvent)=>void}){return <button className={`court-player ${selected?"selected":""}`} onClick={onClick} draggable={draggable} onDragStart={onDragStart}>{p.photo?<img src={p.photo} alt=""/>:<i>{p.name[0]}</i>}<span><b>{p.name}</b><small>#{p.number} · {p.position5||p.position}</small></span></button>}
export default function CourtSetup(){const [draw,setDraw]=useState<Draw>();const [selected,setSelected]=useState<{team:number;index:number}|null>(null);useEffect(()=>{const raw=localStorage.getItem("rachao_court_setup")||localStorage.getItem("rachao_last_draw");if(raw)try{setDraw(JSON.parse(raw))}catch{}},[]);function persist(next:Draw){setDraw(next);localStorage.setItem("rachao_court_setup",JSON.stringify(next))}function swap(team:number,from:number,to:number){if(!draw||from===to)return;const next=structuredClone(draw);[next.teams[team][from],next.teams[team][to]]=[next.teams[team][to],next.teams[team][from]];persist(next);setSelected(null)}function choose(team:number,index:number){if(!selected)return setSelected({team,index});if(selected.team!==team)return setSelected({team,index});swap(team,selected.index,index)}function drop(e:React.DragEvent,team:number,to:number){e.preventDefault();const [sourceTeam,sourceIndex]=e.dataTransfer.getData("text/plain").split(":").map(Number);if(sourceTeam===team)swap(team,sourceIndex,to)}if(!draw)return <Shell><div className="court-missing"><UsersThree size={54}/><h1>Nenhum sorteio encontrado</h1><p>Faça um sorteio antes de organizar as posições em quadra.</p><Link className="primary" href="/sorteio">Ir para sorteio</Link></div></Shell>;return <Shell><div className="page-head"><div><Link className="profile-back" href="/sorteio"><ArrowLeft/> Voltar ao sorteio</Link><p className="eyebrow">ESCALAÇÃO INTERATIVA</p><h1>Posições em quadra</h1><p>Arraste os jogadores ou selecione dois nomes do mesmo time para trocar.</p></div><span className="saved-court"><CheckCircle/> Salvo neste dispositivo</span></div><div className="courts-grid">{draw.teams.map((team,ti)=><section className="court-team" key={ti}><header><span>TIME {String.fromCharCode(65+ti)}</span><h2>{team.length} jogadores</h2></header><div className="volley-layout"><div className="net">REDE</div>{Array.from({length:6},(_,i)=>{const p=team[i];return <div className={`court-slot slot-${i}`} key={i} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,ti,i)}><small>{labels[i]}</small>{p?<PlayerToken p={p} selected={selected?.team===ti&&selected.index===i} onClick={()=>choose(ti,i)} onDragStart={e=>e.dataTransfer.setData("text/plain",`${ti}:${i}`)}/>:<div className="empty-slot">Vazio</div>}</div>})}</div>{team.length>6&&<aside className="bench"><h3>Banco lateral</h3><p>Clique em um jogador do banco e depois em uma posição da quadra para trocar.</p><div>{team.slice(6).map((p,i)=><PlayerToken key={p.id} p={p} selected={selected?.team===ti&&selected.index===i+6} onClick={()=>choose(ti,i+6)} onDragStart={e=>e.dataTransfer.setData("text/plain",`${ti}:${i+6}`)}/>)}</div></aside>}<div className="court-help"><ArrowsLeftRight/> As alterações ficam salvas automaticamente.</div></section>)}</div></Shell>}
